/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface CloudflareEnv ./cloudflare-env.d.ts` (hash: db65c6a1f90b8617d194c726390c79bd)
declare namespace Cloudflare {
	interface Env {
		MCP_OBJECT: DurableObjectNamespace /* MyMCP */;
	}
}
interface CloudflareEnv extends Cloudflare.Env {}
