name: Bug report
description: Report a problem to help improve the project.

labels:
  - bug

body:
  - type: textarea
    attributes:
      label: Description
      description: What happened? What did you expect to happen?
      placeholder: Clear, concise description of the issue.

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Include minimal steps and relevant environment details.
      placeholder: 1) …  2) …  3) …

  - type: textarea
    attributes:
      label: Screenshots or logs
      description: Optional, but helpful for diagnosing the issue.
      placeholder: Paste logs or attach screenshots.

  - type: textarea
    attributes:
      label: Additional context
      description: Any other context that might be relevant.
      placeholder: Links, environment info, etc.
