name: Feature request
description: Suggest an idea or improvement.

labels:
  - enhancement

body:
  - type: textarea
    attributes:
      label: Problem statement
      description: What problem does this solve?
      placeholder: I’m frustrated when … / We need … because …

  - type: textarea
    attributes:
      label: Proposed solution
      description: What would you like to see implemented?
      placeholder: Describe the solution.

  - type: textarea
    attributes:
      label: Alternatives
      description: Other approaches you’ve considered.
      placeholder: Briefly list alternatives.

  - type: textarea
    attributes:
      label: Additional context
      description: Any extra context or references.
      placeholder: Links, screenshots, prior art, etc.
